### ISSUE TITLE
Quick review

### ISSUE THREAD

**Issue by Consolatis** [johanmalm/labwc-gtktheme#1]
https://github.com/johanmalm/labwc-gtktheme/blob/6994044aeac8dcab6d7911421fb8b3075e1d89ac/labwc-gtktheme.py#L17-L23
```python
def fmt(s):
    """ ensure string is at least two characters long """
    return s.zfill(2)
```
#
https://github.com/johanmalm/labwc-gtktheme/blob/6994044aeac8dcab6d7911421fb8b3075e1d89ac/labwc-gtktheme.py#L66
```python
theme[x[1]] = rgb2hex(line) 
```
Or, if you want to make sure your key is a str (in this case it will always be a str):
```python
theme[str(x[1])] = rgb2hex(line) 
```
#
https://github.com/johanmalm/labwc-gtktheme/blob/6994044aeac8dcab6d7911421fb8b3075e1d89ac/labwc-gtktheme.py#L78
This is a no-op, should likely be:
```python
line = line.strip()
```
#
https://github.com/johanmalm/labwc-gtktheme/blob/6994044aeac8dcab6d7911421fb8b3075e1d89ac/labwc-gtktheme.py#L79
I would personally either add a `maxsplit` here so it deals with `:` in values or use two separate variables:
```python
x = line.split(":", maxsplit=1) 
```
```python
key, *values = line.split(":")
```
#
https://github.com/johanmalm/labwc-gtktheme/blob/6994044aeac8dcab6d7911421fb8b3075e1d89ac/labwc-gtktheme.py#L90
```python
with open(themefile, "w") as f:
    f.write(...);
```
Using `open()` as a context manager makes sure that the file will be closed no matter what, no `f.close()` required.

**Comment by johanmalm** [comment]
Sorted.
Trying to parse stuff like `alpha(rgb(1,2,3),0.5)`
Is this pythonic enough? https://gist.github.com/johanmalm/ca37d92d2658f2b027fae21eff5e9ae1
